title: Sam Buckberry
baseurl: ""

date_format: "%Y-%m-%d"

google_analytics:
disqus_shortname:

# Build settings
#markdown: kramdown
#redcarpet:
#  extensions: ['smart', 'tables', 'with_toc_data']
#


markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true
highlighter: rouge
permalink:  pretty
