---
output:
  pdf_document: default
  word_document: default
  html_document: default
---

\begin{center}
\textbf{\large SAM BUCKBERRY} \\
sam.buckberry@uwa.edu.au \\
The University of Western Australia $\bullet$ M316, 35 Stirling Highway, Crawley 6009 \\
\end{center}

## Current position

**Postdoctoral Research Development Fellow (2015 - Present)**  
Lister Lab (epigenetics and genomics)  
The Harry Perkins Institute of Medical Research  
The School of Molecular Sciences  
The University of Western Australia  

## Education

**Doctor of Philosophy - Medicine (2012-2015)**  
The University of Adelaide  
Robinson Research Institute  
Thesis: An integrative analysis of the human placental transcriptome  
*Submitted April 2015 and accepted without change*  
*Awarded the Dean’s commendation for doctoral thesis excellence*  

**Bachelor of Health Science - First Class Honours (2011)**  
The University of Adelaide  
Robinson Research Institute  
*Awarded the Petrucco Honours Scholarship*

**Bachelor of Science (2008-2010)**  
Flinders University  
Extended Major in Biological Sciences  
*Graduated in the top 10% of students*  
*Chancellor’s Commendation 2009 and 2010*

## Research funding

WA Department of Health Merit Award (2020-2021): Repair of abnormal genomic imprinting in human induced pluripotent stem cells through naive reprogramming and targeted epigenome engineering (APP1174766). 
**Buckberry S (CIA) $95,000**

NHMRC-ARC Dementia Research Development Fellowship Grant (2016-2019): The Role of the neuronal methylome in natural brain ageing and the progression of Alzheimer’s Disease (APP1111206).  
**Buckberry S (CIA) $584,644**

NHMRC Peter Doherty Biomedical Early Career Fellowship Award (2016-2019): The role of atypical DNA methylation in neuronal genome regulation and neurodevelopmental disorders (APP1110063).  
**Buckberry S (CIA) $314,644.** *This fellowship was relinquished to accept the grant above.*

Robinson Research Institute Seed Funding (2015-2016): A multi-faceted approach to understanding the consequences of diabetes in early pregnancy.  Brown HM, Nottle M, Gatford K, Dunning K, Breen J & **Buckberry S**. **$25,000** 

Robinson Research Institute Seed Funding (2014-2015): Investigating new mechanisms regulating transcription in the pre-implantation embryo.
Brown HM, Bent SJ, **Buckberry S**, Thompson JG. **$25,000**

\pagebreak

## Awards & scholarships

* Raine Research Prize - Raine Medical Research Foundation (2019). *Awarded for the best biomedical research paper by an early career researcher in Western Australia*
* Ana Africh Stem Cell Research Travel Scholarship (2019)
* Best Oral Presentation by Early Career Researcher at Australasian Genomic Technologies Association (AGTA) conference (2016)
* NHMRC-ARC Dementia Research Fellowship (2016-2019)
* NHMRC Peter Doherty Biomedical Early Career Fellowship (2016-2019) *relinquished*
* Y.W Loke New Investigator Travel Award, IFPA Conference (2015)
* Dean’s Commendation for Doctoral Thesis Excellence (2015)
* Promega PhD Student Award, Lorne Genome Conference (2014)
* ANZPRA New Investigator Award Finalist (2013)
* Healthy Development Adelaide & Channel 7 Children’s Research Foundation PhD Scholarship (2012-2015)
* NHMRC grant-funded PhD top-up scholarship (2012-2015)
* ANZPRA New Investigator Award Finalist (2012)
* Robinson Research Institute Petrucco Honours Scholarship (2011)
* AR Riddle Honours Grant, The University of Adelaide (2011)
* Flinders University Chancellors Commendation (2011)
* Flinders University Chancellors commendation (2010)
* Flinders University Summer Research Scholarship (2010)
* Commonwealth of Australia Education Scholarship (2008-2010)

## Service and community engagement

* Current director on the Australasian Genomics Technology Association (AGTA) executive committee. Key contributions include recently conceiving and establishing the AGTA PhD scholarship
* Speaker - Pint of Science Festival 2018, a forum for communicating contemporary scientific developments to the public
* STEM mentor through The School of Indigenous Studies, The University of Western Australia (2018)
* Placental epigenetics workshop organiser - 2015 International Federation of Placental Associations (IFPA) conference
* Conference organising committee for the 2014 Australian and New Zealand Placental Research Association (ANZPRA) conference

## Peer review

* NHMRC project grant reviewer (2017, 2018)
* Internal project grant reviewer - University of Western Australia 
* Peer reviewer for journals including *Genome Research, Clinical Epigenetics, BMC Genomics, Oncogenomics, Scientific Reports, Placenta, F1000 Research* and *PLoS ONE*.  

## Professional societies 

* Australasian Genomic Technologies Association - Executive committee since 2017
* International Society for Stem Cell Research (ISSCR) - Trainee member
* Stem Cells Australia - ECR member

## Training
* Python for Everybody Specialization - University of Michigan & Coursera (Currently undertaking)
* Data Science Specialization – Johns Hopkins University & Coursera (2014-2015)
* Advanced bioinformatics workshop, Australian Centre for Ancient DNA (2014)
* Software carpentry Boot Camp for Bioinformaticians, Adelaide (2013)
* Advanced bioinformatics workshop, Australian Centre for Ancient DNA (2013)
* EMBL-EBI bioinformatics workshop, Adelaide (2012)
* Advanced bioinformatics workshop, Australian Centre for Ancient DNA (2012)
* Beyond Words public speaking coaching (2012)
* Australian Science Communicators media training (2010) 

## Higher degree by research supervision

* Dawid Maksoa, PhD candidate – Forrest Research Foundation Scholar, The University of Western Australia and the Harry Perkins Institute of Medical Research. Project entitled *'Epigenetics of ageing neurons'*
* Mitchell Bestry, PhD candidate, The University of Western Australia and Telethon Kids Institute. Project entitled *‘The epigenetic origin of fetal alcohol-induced disorders: A cross-species study’*
* Thomas Frazer, BSc (Biotechnology) Honours (2019), The University of Western Australia. *Awarded first class honours*

## Teaching

* Lecturer for the Masters unit *Collecting, analysing and interpreting big data in biology* (2020, 2019). School of Molecular Sciences, The University of Western Australia.
* Lecturer for the Masters unit *The objectives and applications of genomics* (2017). School of Molecular Sciences, The University of Western Australia.
* Teaching for RNA-Seq analysis workshops at BioInfoSummer Conference - Australian Mathematical Sciences Institute and the University of Adelaide (2013).
* Teaching of postgraduate bioinformatics workshops at The University of Adelaide (2013).
* Coordinator and tutor for undergraduate biology Peer Assisted Study Sessions (PASS), Flinders University (2010–2011). In this role, I was mentored by Prof. Karen Burke da Silva (2016 University Teacher of the Year).

## Patents

**Method for reprogramming a cell**: Patent Cooperation Treaty (PCT) application (PCT/AU2019/051296) filed November 2019 for methods related to erasing somatic cell memory in induced pluripotent stem cells. ***Buckberry S***, Liu X, Polo JM and Lister R.
 
## Conference presentations

### Oral presentations

Overcoming the epigenetic barriers to cellular reprogramming. *South Australia Health and Medical Research Institute 2019. Adelaide, Australia.* **Invited presentation**.  

Profiling the shifting epigenetic landscape during human reprogramming. **People's Choice Award**, *Epigenetics Consortium of South Australia Annual Research Meeting 2019. Adelaide Australia.* **Invited presentation**.

Characterising epigenome dynamics during the reprogramming of somatic cells to iPS cells. *Lorne Genome Conference 2017. Lorne, Australia.*

Characterising epigenome dynamics during the reprogramming of somatic cells to iPS cells. **Best ECR oral presentation**, *Australiasian Genomic Technologies Association (AGTA) Conference 2016. Auckland, New Zealand.*

Moving towards integrative epigenomic analyses. *International Federation of Placenta Associations (IFPA) Conference 2015. Brisbane, Australia.* **Invited presentation**.

Integrative analysis of placental transcriptome organization reveals highly conserved regulatory programs and points toward a preeclampsia gene cluster.
**New investigator award session.** *International Federation of Placenta Associations (IFPA) Conference 2015. Brisbane, Australia.* 

Integrative transcriptome meta-analysis reveals widespread sex-biased gene expression patterns in human extra-embryonic tissue. **Promega PhD Student Award**, *Lorne Genome Conference 2014. Lorne Victoria, Australia.*

What can big data tell us about big tummies? *Robinson Research Institute Symposium 2014. Adelaide, Australia.* **Invited presentation.**

Using RNA sequencing to comprehensively profile the transcriptomes of reproductive tissues. *Society for Reproductive Biology Conference 2014. Melbourne, Australia.* **Invited presentation.**

Sexual inequality begins *in utero* with genome-wide differences in the human placental transcriptome. **ANZPRA new investigator award session**,
*Society for Reproductive Biology Conference 2013. Sydney, Australia.*

Using RNA sequencing to quantify placental transcriptomes. *Methods in Reproductive Biology Symposium 2013. Mercy Hospital for Women, Melbourne, Australia.* **Invited presentation.**

Sex-biased gene expression at the human fetal-maternal interface. *Australian Society for Medical Research Annual Meeting 2013. Adelaide, Australia.*

Quantitative allele-specific expression analysis reveals imprinting plasticity of the H19 lincRNA. **ANZPRA new investigator award session**,
*Society for Reproductive Biology Conference 2012. Gold Coast, Australia.*

Allele-specific expression of H19 and IGF2 in the human placenta across gestation. **Honours award session**, *Australian Society for Medical Research Annual Meeting 2012. Adelaide, Australia*.

### Poster presentations

Profiling the genome regulatory landscape of Alzheimer’s Disease at single cell resolution. *NNIDR Australian Dementia Forum 2018. Sydney, Australia* 

Placental transcriptome co-expression analysis reveals conserved regulatory programs and points toward a preeclampsia gene cluster. *Australian Society for Medical Research Annual Meeting 2015. Adelaide, Australia*

Quantitative analysis of imprinted genes in the human placenta reveals developmental stage-specific imprinting plasticity. *Lorne Genome Conference 2013. Lorne, Australia.*

Allele-specific expression of H19, IGF2 and IGF2R in the human placenta through gestation. *Epigenetics Alliance Conference 2012. Adelaide, Australia.*

## Publications

## In press and pre-print manuscripts

Liu X, Ouyang JF, Rossello FJ, Tan JP, Davidson KC, Valdes DS, Schröder J, Sun YBY, Chen J, Knaupp AS, Sun G, Chy HS, Huang Z, Pflueger J, Firas J, Tano V, **Buckberry S**, Paynter JM, Larcombe MR, Choo XY, O’Brien CM, Pastor WA, Chen D, Leichter AL, Naeem H, Tripathi P, Das PP, Grubman A, Powell DR, Laslett AL, David L, Nilsson SK, Clark AT, Lister R, Nefzger CM, Martelotto LG, Rackham OJL and Polo JM (2020). Extra and intra-embryonic programs are established during human reprogramming allowing the derivation of induced trophoblast stem cells. ***Nature*** (accepted article in press)

Grubman A, Choo XY, Chew G, Ouyang JF, Sun G, Croft NP, Rossello FJ. Simmons R, **Buckberry S**, Landin DV, Pflueger J, Vandekolk TH, Abay Z, Liu X, Haynes JM, McLean C, Williams S, Chai SY, Wilson T, Lister R, Pouton CW, Purcell AW, Rackham OJ, Petretto E, and Polo JM (2019). Mouse and human microglial phenotypes in Alzheimer’s disease are controlled by amyloid plaque phagocytosis through Hif1a. ***bioRxiv***

## Peer-reviewed articles

Grubman A, Chew G, Ouyang JF, Sun G, Choo XY, McLean C, Simmons R, **Buckberry S**, Landin DV, Poppe D, Pflueger J, Lister R, Rackham OJ, Petretto E and Polo JM (2019). A single-cell atlas of entorhinal cortex from individuals with Alzheimer’s disease reveals cell-type-specific gene expression regulation. ***Nature Neuroscience*** 22:2087–2097 

de Mendoza A, Hatleberg WL, Pang K, Leininger S, Bogdanovic O, Pflueger J, **Buckberry S**, Technau U, Hejnol A, Adamska M, Degnan BM, Degnan SM and Lister R (2019). Convergent evolution of a vertebrate-like methylome in a marine sponge. ***Nature Ecology and Evolution*** 3;10:1464-1473 

de Mendoza A, Bonnet A, Vargas-Landin DB, Ji N, Hong F, Yang F, Li L, Hori K, Pflueger J, **Buckberry S**, Ohta H, Rosic N, Lesage P, Lin S and Lister R (2018). Recurrent acquisition of cytosine methyltransferases into eukaryotic retrotransposons. ***Nature Communications*** 9;1:1341 

Mayne BT, Leemaqz SY, **Buckberry S**, Rodriguez Lopez CM, Roberts CT, Bianco-Miotto T and Breen J (2018). msgbsR: An R package for analysing methylation-sensitive restriction enzyme sequencing data. ***Scientific Reports*** 8;1:2190 

Knaupp AS^1^, **Buckberry S**^1^, Pflueger J, Lim SM, Ford E, Larcombe MR, Rossello FJ, de Mendoza A, Alaei S, Firas J, Holmes ML, Nair SS, Clark SJ, Nefzger CM, Lister R and Polo JM (2017). Transient and permanent reconfiguration of chromatin and transcription factor occupancy drive reprogramming.   
***Cell Stem Cell*** 21, 1-12 ***^1^ Equal first author*** 

Nefzger CM, Rossello FJ, Chen J, Liu X, Knaupp AS, Firas J, Paynter J, Pflueger J, **Buckberry S**, Lim SM, Williams B, Alaei S, Keshav Faye-Chauhan K, Nilsson SK, Lister R, Ramialison M, Powel DR, Rackham OJL and Polo JM (2017). Cell type of origin dictates the route to pluripotency. ***Cell Reports*** 21:10. 

Wilson RL, Leemaqz SY, Goh Z, McAninch D, Jankovic-Karasoulos T, Leghi GE, Phillips JA, Colafella KM, Tran C, O'Leary S, **Buckberry S**, Pederson S, Robertson SA, Bianco-Miotto T, Roberts CT (2017). Zinc is a critical regulator of placental morphogenesis and maternal hemodynamics during pregnancy in mice. ***Scientific Reports*** 7(1):15137. 

Valensisi C, Andrus C, **Buckberry S**, Doni Jayavelu N, Lund RJ, Lister R and Hawkins RD (2017). Epigenomic Landscapes of hESC-Derived Neural Rosettes: Modeling Neural Tube Formation and Diseases. ***Cell Reports*** 8:20. 

Lumb R, **Buckberry S**, Secker G, Lawrence D and Schwarz Q (2017). Transcriptome profiling reveals expression signatures of cranial neural crest cells arising from different axial levels. ***BMC Developmental Biology*** 17:5. 

**Buckberry S**, Bianco-Miotto T, Bent SJ, Clifton V, Shoubridge C, Shankar K and Roberts CT (2017). Placental transcriptome co-expression analysis reveals conserved regulatory programs across gestation. ***BMC Genomics*** 18:10. 

Mayne B, Bianco-Miotto T, **Buckberry S**, Breen J, Clifton V, Shoubridge C, Roberts CT (2016). Large scale gene expression meta-analysis reveals tissue-specific, sex-biased gene expression in humans. ***Frontiers in Genetics*** 7:183

Highet AR, **Buckberry S**, Mayne BT, Khoda SM, Bianco-Miotto T, Roberts CT (2016). First trimester trophoblasts forming endothelial-like tubes in vitro emulate a ‘blood vessel development’ gene expression profile. ***Gene Expression Patterns*** 21(2):103-10

Bianco-Miotto T, Mayne B, **Buckberry S**, Breen J, Rodriguez Lopez C, Roberts CT (2016). Recent progress towards understanding the role of DNA methylation in human placental development. ***Reproduction*** 152(1): R23–R30.

Highet HR, Khoda SM, **Buckberry S**, Leemaqz S, Bianco-Miotto T, Harrington E, Ricciardelli C & Roberts CT (2015). Hypoxia induced HIF-1/HIF-2 activity alters trophoblast transcriptional regulation and promotes invasion. ***European Journal of Cell Biology*** 94(12):589-602. 

Wilson RL ^1^, **Buckberry S**^1^, Spronk F^1^, Laurence JA, Leemaqz S, O'Leary S, Bianco-Miotto T, Du J, Anderson PH & Roberts CT (2015). Vitamin D Receptor Gene Ablation in the Conceptus Has Limited Effects on Placental Morphology, Function and Pregnancy Outcome. ***PLoS ONE*** 10(6):e0131287. ***^1^ Equal first author***

**Buckberry S**, Bianco-Miotto T, Bent SJ, Dekker GA & Roberts CT (2014). Integrative transcriptome meta-analysis reveals widespread sex-biased gene expression at the human fetal–maternal interface. ***Molecular Human Reproduction*** 20(8):810-9. 

**Buckberry S**, Bent SJ, Bianco-Miotto T & Roberts CT (2014). MassiR: a method for predicting the sex of samples in gene expression microarray datasets. ***Bioinformatics*** 30(14):2084-5. 

**Buckberry S**, Bianco-Miotto T & Roberts CT (2014). Imprinted and X-linked non-coding RNAs as potential regulators of human placental function, ***Epigenetics*** 9(1):81-9. 

Gatford KL, Heinemann GK, Thompson SD, Zhang JV, **Buckberry S**, Owens J, Dekker GA & Roberts CT (2014). Circulating IGF1 and IGF2 and SNP genotypes in pregnant and non-pregnant women and men. ***Endocrine Connections*** 3(3):138–149. 

**Buckberry S**, Bianco-Miotto T, Hiendleder S & Roberts CT (2012). Quantitative Allele-Specific Expression and DNA Methylation Analysis of H19, IGF2 and IGF2R in the Human Placenta across Gestation Reveals H19 Imprinting Plasticity. ***PLoS ONE*** 7(12):e51210. 

**Buckberry S** & Burke da Silva K (2012). Evolution: improving the understanding of undergraduate students with an active pedagogical approach. ***Evolution, Education & Outreach*** 5(2):266-273. 

## Book chapters

Stuart T, **Buckberry S**, Lister R (2018). Approaches for the Analysis and Interpretation of Whole Genome Bisulfite Sequencing Data. ***Methods in Molecular Biology*** 1767:299-310.  

## Workshop reports

Bianco-Miotto T, Blundell C, **Buckberry S**, Chamley L, Chong S, Cottrell E, Dawson P, Hanna C, Holland O, Lewis RM, Moritz K, Myatt L, Perkins AV, Powell T, Saffery R, Sferruzzi-Perri A, Sibley C, Simmons D & O'Tierney-Ginn PF (2016). IFPA meeting 2015 workshop report I: placental mitochondrial function, transport systems and epigenetics. ***Placenta*** 48(S3-36). 

## Datasets

**Buckberry S**, Spronk F, Wilson RL, Laurence JA, Bianco-Miotto T, Leemaqz S, O'Leary S, Anderson PH & Roberts CT (2015). The effect of Vdr gene ablation on global gene expression in the mouse placenta. ***Genomics Data*** 6:72-73. 

## Feature articles

**Buckberry S** & Roberts CT (2014). Why are males more at risk in the womb? ***Australasian Science***, November 2014. 