---
output:
    pdf_document: default
    
---

\begin{center}
\textbf{\large SAM BUCKBERRY} \\
sam.buckberry@telethonkids.org.au \\
Black Ochre Data Labs $\bullet$ Telethon Kids Institute \\

\end{center}

## Current position (Jan 2022 - present)
**Bioinformatician - Black Ochre Data Labs**  
Indigenous Genomics - Telethon Kids Institute (Perth WA)

Here I lead research on developing epigenetic biomarkers of Type-2 diabetes in Indigenous Australian populations. I am also a technical lead in the development of the data architecture, security and standards for research using indigenous genomics data. 

## Current appointments

Australasian Genomics Technology Association (AGTA) - Executive Committee Member  
Human Research Ethics Committee Member - WA Department of Health

## Education

**Doctor of Philosophy (2012-2015)**  
The University of Adelaide  
Robinson Research Institute  
Thesis: An integrative analysis of the human placental transcriptome  
*Awarded the Dean’s commendation for doctoral thesis excellence*  

**Bachelor of Health Science - First Class Honours (2011)**  
The University of Adelaide  
Robinson Research Institute  
*Awarded the Petrucco Honours Scholarship*

**Bachelor of Science (2008-2010)**  
Flinders University  
Extended Major in Biological Sciences  
*Chancellor’s Commendation 2009 and 2010*

## Previous role

**Postdoctoral Research Fellow - Genome Bioinformatics (2015-2022)**  
Lister Lab (epigenetics and genomics)  
Harry Perkins Institute of Medical Research  
The School of Molecular Sciences  
The University of Western Australia  

I was a senior bioinformatician in Prof. Ryan Lister's group for 6.5 years.
Here I established custom bioinformatics workflows for complex questions in fields such stem cell biology, neuroscience, evolution and epigenetic engineering. My work involved the analysis and integration of multiple omics data types including whole genome DNA methylation (WGBS), ATAC-seq, RNA-seq, ChIP-seq and single-cell omics technologies.   

## Research funding

Google Cloud Research Grant (2021): Solving the problem of epigenetic memory in reprogrammed human cells. **CIA Buckberry $6,796**

WA Department of Health Merit Award (2020): Repairing abnormal genomic imprinting in induced pluripotent stem cells with naive reprogramming and targeted epigenome engineering. **CIA Buckberry $95,000**

NHMRC-ARC Dementia Research Development Fellowship Grant (2016-2019): The Role of the neuronal methylome in natural brain ageing and the progression of Alzheimer’s Disease (APP1111206).  
**CIA Buckberry $584,644**

NHMRC Peter Doherty Biomedical Early Career Fellowship Award (2016-2019): The role of atypical DNA methylation in neuronal genome regulation and neurodevelopmental disorders (APP1110063).  
**CIA Buckberry $314,644.** *This fellowship was relinquished to accept the grant above.*

Robinson Research Institute Seed Funding (2015-2016): A multi-faceted approach to understanding the consequences of diabetes in early pregnancy.  Brown HM, Nottle M, Gatford K, Dunning K, Breen J & **Buckberry S**. **$25,000**

Robinson Research Institute Seed Funding (2014-2015): Investigating new mechanisms regulating transcription in the pre-implantation embryo.
Brown HM, Bent SJ, **Buckberry S**, Thompson JG. **$25,000**

## Selected awards

* Finalist - Woodside Early Career Scientist of the Year (2020) -  WA Premier's Science Awards.
* Raine Research Prize - Raine Medical Research Foundation (2019). *Awarded for the best biomedical research paper by an early career researcher in Western Australia*
* Ana Africh Stem Cell Research Travel Scholarship (2019)
* Best Oral Presentation by Early Career Researcher at Australasian Genomic Technologies Association (AGTA) conference (2016)
* Dean’s Commendation for Doctoral Thesis Excellence (2015)
* Promega PhD Student Award, Lorne Genome Conference (2014)

## Patents
**Method for Reprogramming a Cell** (Buckberry, Liu, Polo, Lister)  
For 2017-2022, I led a research program on correcting aberrant DNA methylation in human stem and discovered how to erase epigenetic memory and developed this into a PCT international patent.  
PCT patent application #WO2021102500  

## Publications

**Papers: 30** (8 first-author)  
**H-index: 21**  
**Citations: 1,332**  

I have published 30 peer-reviewed papers in journals including ***Nature, Cell Stem Cell, Nature Neuroscience, Nature Ecology and Evolution*** and ***Genome Biology***. 

See my [Google Scholar page](https://scholar.google.com/citations?user=b--b_fUAAAAJ&hl=en) for full publication listings.  
[https://scholar.google.com/citations?user=b--b_fUAAAAJ&hl=en](https://scholar.google.com/citations?user=b--b_fUAAAAJ&hl=en)